      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
        "-instances=$(STORAGE_INSTANCE)=tcp:3306",
                  "-credential_file=/var/secrets/google/key.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
            readOnly: true
        envFrom:
          - configMapRef:
              name: deploy-config

