apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: trillian-log-signer
  name: trillian-logsigner-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: trillian-log-signer
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: spanner-key
      containers:
      - command: ["/go/bin/trillian_log_signer",
        "$(STORAGE_FLAG)",
        "--storage_system=$(STORAGE_SYSTEM)",
        "--quota_system=noop",
        "--http_endpoint=0.0.0.0:8091",
        "--sequencer_guard_window=0s",
        "--sequencer_interval=1s",
        "--num_sequencers=1",
        "--batch_size=1",
        "--cloudspanner_dequeue_bucket_fraction=0",
        "--cloudspanner_num_channels=10",
        "--cloudspanner_min_open_sessions=1000",
        "--cloudspanner_write_sessions=1",
        "--force_master=true",
        "--alsologtostderr",
        "--vmodule=sequencer=2,log_operation_manager=2,subtree_cache=2,log_storage=2",
        ]
        envFrom:
          - configMapRef:
              name: deploy-config
        # Update this with the name of your project:
        image: gcr.io/trillian-opensource-ci/log_signer:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1.5"
          requests:
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8091/metrics
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: trillian-log-signer
        ports:
        - containerPort: 8091
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      nodeSelector:
        cloud.google.com/gke-nodepool: signer-pool
      restartPolicy: Always
status: {}
