# This configmap is for running Trillian with a MySQL database on Kubernetes.
# You'll want to update the storage-flag below with the correct configuration
# info for the database.
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-config
  namespace: default
data:
  # Update this with the name of your project:
  cloud-project: trillian-opensource-ci
  # Update this with your DB connection string:
  storage-flag: --mysql_uri=test:zaphod@tcp(db:3306)/test
  storage-system: mysql
  google-application-credentials: /var/secrets/google/key.json

