apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-config
  namespace: default
data:
  STORAGE_SYSTEM: mysql
  STORAGE_INSTANCE: "${PROJECT_ID}:${REGION}:trillian-cloudsql"
  STORAGE_FLAG: --mysql_uri=trillian-db-user:4q8f9jvreuf@tcp(127.0.0.1:3306)/trillian-db
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
  SIGNER_DEQUEUE_BUCKET_FRACTION: "0.0078"
  SIGNER_BATCH_SIZE: "1800"
  SIGNER_INTERVAL: "2ms"
  SIGNER_NUM_SEQUENCERS: "10"
  SIGNER_RESIGN_ODDS: "1000"
